[project]
name = "hackathon-local"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.9.3",
    "mdanalysis>=2.8.0",
    "pandas>=2.2.3",
    "scikit-learn>=1.5.2",
]
